### PR TITLE
Quote Removal Suggestion

### PR DESCRIPTION
**Pull request by sgarrison05**
I created a branch that just has the extra quotes removed, barring you do not have any spaces.  I tested it both with and without arguments.  It works.  I also tested it without the directory created with no issues.  I hope this helps your project.

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Can you make a new PR where the only commit is you removing the quotes?

**Comment by sgarrison05** [comment]
I thought I already did that. I created a branch with just the quotes removed and created a pull request. Shon ***@***.*** Apr 15, 2023, at 1:26 PM, Nick Janetakis ***@***.***> wrote:﻿
Hi,
Can you make a new PR where the only commit is you removing the quotes?

**Comment by nickjj** [comment]
There's still (4) commits associated with this PR.

**Comment by nickjj** [comment]
Also is the commit message accurate?

I thought we were good to go if it has spaces or not based on the other PR.

Your commit message contains:

>  As long as there are no spaces the extra quotes are not needed.

We would want to support spaces in the path.

**Comment by sgarrison05** [comment]
Ok. I’ll look at it. I’m sorry. This is my first ever pull request. I’m still learning with git. Shon ***@***.*** Apr 15, 2023, at 5:38 PM, Nick Janetakis ***@***.***> wrote:﻿
There's still (4) commits associated with this PR.

**Comment by nickjj** [comment]
It's all good. The easiest way would probably be to:

- Delete your existing fork
- Fork this repo again
- Make a new branch
- Make the single change you want to remove the quotes and commit it
- Push that branch up to your fork
- Open the PR here

There are ways to "squash" commits or reset things in other ways but the above is a general "when in doubt, start from scratch" way of doing things if you aren't used to using a number of git commands.

**Comment by sgarrison05** [comment]
Ok...I deleted my repository, re-forked it, removed the quotes on a branch called quote_rm, and did a pull request.  Whew...I hope that did it.  Let me know if you need anything else.

**Pull request closed without merging**
